### ISSUE TITLE
Provide with offset for system symbol files

### ISSUE THREAD

**Issue by Aashima89** [getsentry/symbolicator#205] opened 2020-03-18 18:33 UTC
since we cant get lineno for system symbol files
is it possible to return offset - how atos returns offset

unsymbolcated 3 UIKitCore 0x00000001fd2e9890 0x1fcfc8000 + 3283088
Symbolciated -> UIKit -[UICollectionView _performBatchUpdates:completion:invalidationContext:]+80

For a developer when they compare crash reports, it seems to be a useful information to have offset.

see https://developer.apple.com/library/archive/technotes/tn2151/_index.html

**Comment by jan-auer** [comment] 2020-03-18 18:40
That should work, we can add the offset relative to the module to the stacktrace response schema. It can be trivially calculated by subtracting the module base address from the frame's address. While this attribute would be somewhat redundant, I can see that it would make the responses more convenient to interpret.

In Sentry, we do this in the UI (here a screenshot from an unsymbolicated event):

![image](https://user-images.githubusercontent.com/1433023/76995475-3377a280-6950-11ea-873c-e8544e6613e2.png)

**Comment by Aashima89** [comment] 2020-03-18 21:46
yeah that offset can be calculated to return some integer value for symbolicated events

**Comment by mitsuhiko** [comment] 2020-03-18 21:57
What are you trying to do? This issue together with the last two about almost the same topic all point towards you wanting something from this system what it's not intended on doing.

**Comment by Aashima89** [comment] 2020-03-19 14:17
was majorly concerned by getting lineno for system symbol files. if not that then offset. We have customers seeing this stacktrace. Just inclined towards what we can provide user more on the stacktrace side based on what atos provides

**Comment by mark-saarinen** [comment] 2020-11-25 22:33
To confirm, from the symbolicator frame response is the trivial calculation **instruction_addr - sym_addr**?

**Comment by mark-saarinen** [comment] 2020-11-26 00:51
To confirm, from the symbolicator frame response is the trivial calculation instruction_addr - sym_addr?

**Comment by mk4437** [comment] 2020-11-26 00:52
To confirm, from the symbolicator frame response is the trivial calculation instruction_addr - sym_addr?

**Comment by jan-auer** [comment] 2020-11-26 11:03
The correct way to compute this is via `instruction_addr - module.image_addr`, where `module` is the respective entry in the `modules` list that this frame points to. 

We are looking into extending the input and output format at the moment, so we can add an image-relate output address in addition. 

To clarify, would you need relative addresses compatible with `addr2line`? In that case, the calculation needs to take the module's stated load address into account for MachO and ELF symbols. To give an example:

- An ELF module is loaded at `0x10000` 
- Its stated loaded address is `0x40000`
- There is a frame at absolute address `0x10100`.
- The relative address `0x100` (absolute address - loaded address)
- The stated relative address compatible with _addr2line_ is `0x40100`, since this is where the symbol is stated in the original file.

**Comment by mk4437** [comment] 2021-02-09 19:32
I'm not sure if this came across in the earlier discussion, but what remains confusing here to us is that the symbolicator response contains a "lineno" field that is getting set to a non-zero value for the app's own stackframes but is always zero for any system stackframes.   Is this expected behavior, and if so what is the reasoning behind  it?  

Using a sample request, the only way I was able to calculate a non-huge (I mean really huge) number from the response (i.e., less than a few K, in some cases < 100) was to evaluate `instruction_addr - sym_addr`.   I'm looking at additional records to see how that approach holds up.

**Comment by jan-auer** [comment] 2021-02-10 08:17
Resolving the line number requires full debug information, which is often not available for system modules. For instance, the symbols publicly available for `UIKitCore` only contain a symbol table, but no DWARF information. Hence, it is possible to resolve function names, but no file or line information. 

Symbolicator should probably omit the `lineno` field, but outputs `0` in some cases. We should certainly improve that.

**Comment by Swatinem** [comment] 2023-01-23 11:33
Symbolicator should already return the relevant bits of information and there is enough discussion in this thread to explain how to use that.

**Closed by Swatinem** 2023-01-23 11:33 UTC
