### ISSUE TITLE
Error while fetching cficache: computation was canceled internally

### ISSUE THREAD

**Issue by hulucc** [getsentry/symbolicator#162] opened 2019-12-23 13:13 UTC
Server: sentry, snuba and symbolicator from the latest docker image in k8s.

Client: sentry-native 0.14, offical exmaple_crash.exe build by vs2017 with debug config on win10 1903

Upload debug info by:
`sentry-cli upload-dif -o sentry -p native-cc --include-sources --wait -- .`

Symbolicator log:
```
symbolicator-0 symbolicator thread 'tokio-runtime-worker-0' panicked at 'slice index starts at 70397 but ends at 63488', src/libcore/slice/mod.rs:2591:5
symbolicator-0 symbolicator stack backtrace:
symbolicator-0 symbolicator    0: <unknown>
symbolicator-0 symbolicator    1: core::fmt::write
symbolicator-0 symbolicator    2: <unknown>
symbolicator-0 symbolicator    3: <unknown>
symbolicator-0 symbolicator    4: <unknown>
symbolicator-0 symbolicator    5: std::panicking::rust_panic_with_hook
symbolicator-0 symbolicator    6: <unknown>
symbolicator-0 symbolicator    7: rust_begin_unwind
symbolicator-0 symbolicator    8: core::panicking::panic_fmt
symbolicator-0 symbolicator    9: core::slice::slice_index_order_fail
symbolicator-0 symbolicator   10: goblin::pe::exception::UnwindInfo::parse
symbolicator-0 symbolicator   11: goblin::pe::exception::ExceptionData::get_unwind_info
symbolicator-0 symbolicator   12: symbolic_minidump::cfi::CfiCache::from_object
symbolicator-0 symbolicator   13: <unknown>
symbolicator-0 symbolicator   14: <unknown>
symbolicator-0 symbolicator   15: <unknown>
symbolicator-0 symbolicator   16: __rust_maybe_catch_panic
symbolicator-0 symbolicator   17: <unknown>
symbolicator-0 symbolicator   18: <unknown>
symbolicator-0 symbolicator   19: <unknown>
symbolicator-0 symbolicator   20: <unknown>
symbolicator-0 symbolicator   21: <unknown>
symbolicator-0 symbolicator   22: __rust_maybe_catch_panic
symbolicator-0 symbolicator   23: <unknown>
symbolicator-0 symbolicator   24: <unknown>
symbolicator-0 symbolicator   25: tokio_threadpool::worker::Worker::run
symbolicator-0 symbolicator   26: <unknown>
symbolicator-0 symbolicator   27: <unknown>
symbolicator-0 symbolicator   28: <unknown>
symbolicator-0 symbolicator   29: <unknown>
symbolicator-0 symbolicator   30: <unknown>
symbolicator-0 symbolicator   31: <unknown>
symbolicator-0 symbolicator   32: <unknown>
symbolicator-0 symbolicator   33: <unknown>
symbolicator-0 symbolicator   34: __rust_maybe_catch_panic
symbolicator-0 symbolicator   35: <unknown>
symbolicator-0 symbolicator   36: <unknown>
symbolicator-0 symbolicator   37: <unknown>
symbolicator-0 symbolicator   38: start_thread
symbolicator-0 symbolicator   39: __clone
symbolicator-0 symbolicator note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
symbolicator-0 symbolicator 2019-12-23T12:54:02Z [symbolicator::actors::symbolication] INFO: Error while fetching cficache: computation was canceled internally
symbolicator-0 symbolicator
symbolicator-0 symbolicator stack backtrace:
symbolicator-0 symbolicator    0: <unknown> (0x55b28bcad468)
symbolicator-0 symbolicator    1: failure::backtrace::Backtrace::new::hae2649ba15221c47 (0x55b28bcad620)
symbolicator-0 symbolicator    2: <unknown> (0x55b28b549238)
symbolicator-0 symbolicator    3: <unknown> (0x55b28b489b28)
symbolicator-0 symbolicator    4: <unknown> (0x55b28b54d110)
symbolicator-0 symbolicator    5: <unknown> (0x55b28b47fab2)
symbolicator-0 symbolicator    6: <unknown> (0x55b28b2b93c4)
symbolicator-0 symbolicator    7: <unknown> (0x55b28b466223)
symbolicator-0 symbolicator    8: <unknown> (0x55b28b2cc3c9)
symbolicator-0 symbolicator    9: <unknown> (0x55b28b2c1896)
symbolicator-0 symbolicator   10: <unknown> (0x55b28b47951d)
symbolicator-0 symbolicator   11: <unknown> (0x55b28b4c94b3)
symbolicator-0 symbolicator   12: __rust_maybe_catch_panic (0x55b28bce5a1a)
symbolicator-0 symbolicator   13: <unknown> (0x55b28b41f471)
symbolicator-0 symbolicator   14: <unknown> (0x55b28b3dffba)
symbolicator-0 symbolicator   15: <unknown> (0x55b28b762892)
symbolicator-0 symbolicator   16: <unknown> (0x55b28b78e81b)
symbolicator-0 symbolicator   17: <unknown> (0x55b28b777929)
symbolicator-0 symbolicator   18: <unknown> (0x55b28b78f0d6)
symbolicator-0 symbolicator   19: <unknown> (0x55b28b76bab3)
symbolicator-0 symbolicator   20: <unknown> (0x55b28b76b637)
symbolicator-0 symbolicator   21: <unknown> (0x55b28b76848d)
symbolicator-0 symbolicator   22: <unknown> (0x55b28b769199)
symbolicator-0 symbolicator   23: <unknown> (0x55b28b74b090)
symbolicator-0 symbolicator   24: <unknown> (0x55b28b786928)
symbolicator-0 symbolicator   25: <unknown> (0x55b28b786eb6)
symbolicator-0 symbolicator   26: __rust_maybe_catch_panic (0x55b28bce5a1a)
symbolicator-0 symbolicator   27: <unknown> (0x55b28b7905f6)
symbolicator-0 symbolicator   28: <unknown> (0x55b28bccc95f)
symbolicator-0 symbolicator   29: <unknown> (0x55b28bce4d80)
symbolicator-0 symbolicator   30: start_thread (0x7f188d8334a4)
symbolicator-0 symbolicator   31: __clone (0x7f188e7bdd0f)
symbolicator-0 symbolicator   32: <unknown> (0x0)

```

Related file:
```
root@symbolicator-0:/data/cficaches/7# head -n 10 sentry_project_95_sentryinternal
STACK CFI INIT aac90 4c .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI aac90 .cfa: $rsp 256 +
STACK CFI INIT aacf0 4c .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI aacf0 .cfa: $rsp 256 +
STACK CFI INIT aad50 4c .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI aad50 .cfa: $rsp 256 +
STACK CFI INIT aadb0 4c .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI aadb0 .cfa: $rsp 256 +
STACK CFI INIT aae10 4c .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI aae10 .cfa: $rsp 256 +
root@symbolicator-0:/data/cficaches/7# tail -n 10 sentry_project_95_sentryinternal
STACK CFI INIT 1f1320 34 .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI 1f1320 .cfa: $rsp 256 +
STACK CFI INIT 1f1370 34 .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI 1f1370 .cfa: $rsp 256 +
STACK CFI INIT 1f13c0 34 .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI 1f13c0 .cfa: $rsp 256 +
STACK CFI INIT 1f1410 34 .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI 1f1410 .cfa: $rsp 256 +
STACK CFI INIT 1f1460 15 .cfa: $rsp 8 + .ra: .cfa 8 - ^
STACK CFI 1f1460 .cfa: $rsp 48 +
```

Sentry:
![image](https://user-images.githubusercontent.com/4343900/71359737-8bf50900-25c8-11ea-80bc-c898712c6867.png)

**Comment by Swatinem** [comment] 2022-02-21 10:37
This seems to have been caused by a panic in `goblin::pe::exception::UnwindInfo::parse`, which I bet was long fixed. We should also be handling panics better by now, so closing this.

**Closed by Swatinem** 2022-02-21 10:37 UTC
